### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Aryan807** [denesfilotas/vscode-blitz3d#5]
There's another issue: opening my project gives the following exception
```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'push')
t checkForArithmeticErrors (d:\Projects\vscode-blitz3d\out\context\analyzer.js:1380:21)
	at BlitzAnalyzer.parseExpr2 (d:\Projects\vscode-blitz3d\out\context\analyzer.js:833:17)
	at BlitzAnalyzer.parseExpr1 (d:\Projects\vscode-blitz3d\out\context\analyzer.js:752:24)
	at BlitzAnalyzer.parseExpr (d:\Projects\vscode-blitz3d\out\context\analyzer.js:748:21)
	at BlitzAnalyzer.parseIf (d:\Projects\vscode-blitz3d\out\context\analyzer.js:695:21)
	at BlitzAnalyzer.parseIf (d:\Projects\vscode-blitz3d\out\context\analyzer.js:703:33)
	at BlitzAnalyzer.parseIf (d:\Projects\vscode-blitz3d\out\context\analyzer.js:703:33)
	at BlitzAnalyzer.parseIf (d:\Projects\vscode-blitz3d\out\context\analyzer.js:703:33)
	at BlitzAnalyzer.parseStmtSeq (d:\Projects\vscode-blitz3d\out\context\analyzer.js:169:30)
	at BlitzAnalyzer.parseIf (d:\Projects\vscode-blitz3d\out\context\analyzer.js:699:22)
	at BlitzAnalyzer.parseStmtSeq (d:\Projects\vscode-blitz3d\out\context\analyzer.js:169:30)
	at new BlitzAnalyzer (d:\Projects\vscode-blitz3d\out\context\analyzer.js:35:14)
	at createLaunchContext (d:\Projects\vscode-blitz3d\out\context\context.js:53:32)
	at initializeContext (d:\Projects\vscode-blitz3d\out\context\context.js:220:5)
	at activate (d:\Projects\vscode-blitz3d\out\extension.js:29:37)
	at j.ib (d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:13251)
	at j.hb (d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:12964)
	at d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:11089
	at async u.n (d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6255)
	at async u.m (d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6218)
	at async u.l (d:\Softwares\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:5675)
```

**Comment by Aryan807** [comment]
Update: Putting `this.diagnostics.set(uri, []);` in the constructors of BlitzAnalyser and BlitzParser seems to fix the issue.
